<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>apiary</string>
		<string>apib</string>
	</array>
	<key>name</key>
	<string>Apiary Blueprint</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#+.*$</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(\+|\*|\-).*$</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.apiary</string>
	<key>uuid</key>
	<string>5fb76a53-14d0-42db-ae85-018236c1612a</string>
</dict>
</plist>
